### ISSUE TITLE
Docusarus?

### ISSUE THREAD

**Issue by Inglan2** [Contentgiver/ContentGiver.github.io#4]
Docusarus has more features and I know enough javascript to use it. I think we should migrate to it for the website. I mainly want a better home page and MkDocs Material makes that a little harder. Should I try and migrate?
@nathblade16

**Comment by nathblade16** [comment]
sure

**Comment by Inglan2** [comment]
Ok ill start migration

**Comment by Inglan2** [comment]
Just created branch

**Comment by Inglan2** [comment]
damn should have commited my changes. now i can't undo...
![20240828_14h44m02s_grim](https://github.com/user-attachments/assets/12d00480-af3b-4ca9-885b-6028cc803181)
yeah idk what im doing

**Comment by nathblade16** [comment]
> damn should have commited my changes. now i can't undo... ![20240828_14h44m02s_grim](https://private-user-images.githubusercontent.com/117789688/362136489-12d00480-af3b-4ca9-885b-6028cc803181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjA2NTMsIm5iZiI6MTcyNDgyMDM1MywicGF0aCI6Ii8xMTc3ODk2ODgvMzYyMTM2NDg5LTEyZDAwNDgwLWFmM2ItNGNhOS04ODViLTYwMjhjYzgwMzE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwNDQ1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2M3Njc3ZGE0NzczOGUxNmFkNjhlZjk1ZGE1MzM5OTQ3MTNjMTJiMWYzOThiZTFmMjlkMDM3OTdhZmFhNjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f2m36MptqxSSF7xygwhIIwxhoHcVudoQO4Ud02zrtWQ) yeah idk what im doing

you know github history is a thing right???

**Comment by Inglan2** [comment]
wdym

**Comment by Inglan2** [comment]
like commit history

**Comment by nathblade16** [comment]
yes

**Comment by Inglan2** [comment]
no i just didnt commit whenever i changed something

**Comment by Inglan2** [comment]
but fixed now

**Comment by Inglan2** [comment]
just pushed my changes!

now its just

- [x] Home page
- [ ] Actions workflow
